/// Integration tests that upload real DOCX fixture files to the /convert endpoint
/// and assert extraction correctness for each scenario.
///
/// Fixtures are generated by tests/fixtures/generate_fixtures.py.
/// Each test validates a distinct extractor code path:
///   - article_full_research      → happy path, IEEE refs via "References" heading
///   - article_bibliography_alias → "Bibliography" heading alias for references
///   - article_no_references      → no ref section → parser warning emitted
///   - article_review_paper       → "Works Cited" heading alias, 8 refs, 6 body sections

use axum::http::StatusCode;
use axum_test::TestServer;
use std::io::Write;

fn build_router() -> axum::Router {
    docx_jats_backend::api::routes::build_router()
}

fn multipart_body(docx_bytes: &[u8]) -> (String, Vec<u8>) {
    let boundary = "FixtureBoundary5678";
    let mut body = Vec::new();
    write!(body, "--{boundary}\r\n").unwrap();
    write!(
        body,
        "Content-Disposition: form-data; name=\"file\"; filename=\"test.docx\"\r\n"
    )
    .unwrap();
    write!(
        body,
        "Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document\r\n\r\n"
    )
    .unwrap();
    body.extend_from_slice(docx_bytes);
    write!(body, "\r\n--{boundary}--\r\n").unwrap();
    (format!("multipart/form-data; boundary={boundary}"), body)
}

fn load_fixture(name: &str) -> Vec<u8> {
    std::fs::read(format!("tests/fixtures/{name}"))
        .unwrap_or_else(|e| panic!("fixture '{name}' not found — run generate_fixtures.py first: {e}"))
}

fn has_warning(warnings: &serde_json::Value, fragment: &str) -> bool {
    warnings
        .as_array()
        .unwrap_or(&vec![])
        .iter()
        .any(|w| w.as_str().unwrap_or("").contains(fragment))
}

// ── happy path ────────────────────────────────────────────────────────────────

/// Full research paper: Title style + Heading1 "Abstract" heuristic + 5 IEEE refs.
/// Verifies the main extraction pipeline produces a well-formed JATS document.
#[tokio::test]
async fn test_full_research_article() {
    let server = TestServer::new(build_router());
    let (ct, body) = multipart_body(&load_fixture("article_full_research.docx"));

    let response = server.post("/convert").content_type(&ct).bytes(body.into()).await;
    assert_eq!(response.status_code(), StatusCode::OK);

    let json: serde_json::Value = response.json();
    assert_eq!(json["success"], true, "conversion must succeed");

    let meta = &json["metadata"];
    assert!(
        meta["title"].as_str().unwrap_or("").contains("Blorfification"),
        "title not extracted from Title-style paragraph"
    );
    assert_eq!(meta["has_abstract"], true, "abstract must be detected");
    assert_eq!(meta["reference_count"], 5, "expected 5 IEEE references");
    assert!(
        meta["section_count"].as_u64().unwrap_or(0) >= 7,
        "expected at least 7 sections (6 body + References)"
    );

    let xml = json["xml"].as_str().unwrap();
    assert!(xml.contains("<article"), "JATS root element missing");
    assert!(xml.contains("<article-title>"), "title element missing");
    assert!(xml.contains("<abstract>"), "abstract element missing");
    assert!(xml.contains("<ref-list>"), "ref-list missing");
    assert!(xml.contains("<mixed-citation>"), "citation entries missing");

    assert!(
        !has_warning(&json["warnings"], "Could not determine document title"),
        "unexpected title warning — Title style not recognised"
    );
    assert!(
        !has_warning(&json["warnings"], "No abstract found"),
        "unexpected abstract warning — Abstract heuristic failed"
    );
    assert!(
        !has_warning(&json["warnings"], "No references section found"),
        "unexpected references warning"
    );
}

// ── reference heading aliases ─────────────────────────────────────────────────

/// "Bibliography" is a recognised alias for the references section heading.
/// The extractor must find 4 APA-style entries and emit no missing-ref warning.
#[tokio::test]
async fn test_bibliography_heading_alias() {
    let server = TestServer::new(build_router());
    let (ct, body) = multipart_body(&load_fixture("article_bibliography_alias.docx"));

    let response = server.post("/convert").content_type(&ct).bytes(body.into()).await;
    assert_eq!(response.status_code(), StatusCode::OK);

    let json: serde_json::Value = response.json();
    assert_eq!(json["success"], true);

    let meta = &json["metadata"];
    assert!(
        meta["title"].as_str().unwrap_or("").contains("Quonk Enterprises"),
        "title not extracted"
    );
    assert_eq!(meta["has_abstract"], true);
    assert_eq!(
        meta["reference_count"], 4,
        "Bibliography heading must be recognised as ref-section alias"
    );
    assert!(meta["section_count"].as_u64().unwrap_or(0) >= 4);

    let xml = json["xml"].as_str().unwrap();
    assert!(xml.contains("<ref-list>"), "references not emitted to JATS");

    assert!(
        !has_warning(&json["warnings"], "No references section found"),
        "Bibliography alias not recognised — ref warning emitted unexpectedly"
    );
}

/// "Works Cited" is the third recognised alias for the references section.
/// The extractor must find all 8 entries and emit no missing-ref warning.
#[tokio::test]
async fn test_works_cited_heading_alias() {
    let server = TestServer::new(build_router());
    let (ct, body) = multipart_body(&load_fixture("article_review_paper.docx"));

    let response = server.post("/convert").content_type(&ct).bytes(body.into()).await;
    assert_eq!(response.status_code(), StatusCode::OK);

    let json: serde_json::Value = response.json();
    assert_eq!(json["success"], true);

    let meta = &json["metadata"];
    assert!(
        meta["title"].as_str().unwrap_or("").contains("Systematic Review"),
        "title not extracted"
    );
    assert_eq!(meta["has_abstract"], true);
    assert_eq!(
        meta["reference_count"], 8,
        "Works Cited heading must be recognised as ref-section alias"
    );
    assert!(
        meta["section_count"].as_u64().unwrap_or(0) >= 6,
        "expected at least 6 body sections"
    );
    // Author line "Snazzleton, A., Frumpleston, B., & Zibbitova, C." must be
    // split into 3 individual authors by the APA heuristic.
    assert_eq!(
        meta["author_count"], 3,
        "expected 3 authors from APA-format positional line"
    );
    let doc = &json["document"];
    let authors = doc["authors"].as_array().expect("authors must be an array");
    assert_eq!(authors[0]["name"], "Snazzleton, A.", "first author name mismatch");
    assert_eq!(authors[1]["name"], "Frumpleston, B.", "second author name mismatch");
    assert_eq!(authors[2]["name"], "Zibbitova, C.", "third author name mismatch");

    let xml = json["xml"].as_str().unwrap();
    assert!(xml.contains("<ref-list>"));
    assert!(xml.contains("<abstract>"));

    assert!(
        !has_warning(&json["warnings"], "No references section found"),
        "Works Cited alias not recognised"
    );
    assert!(
        !has_warning(&json["warnings"], "Could not determine document title")
    );
}

// ── warning path ──────────────────────────────────────────────────────────────

/// A document with no references section must still convert successfully
/// but must emit a warning and produce no <back>/<ref-list> in the JATS output.
#[tokio::test]
async fn test_no_references_warns_and_omits_ref_list() {
    let server = TestServer::new(build_router());
    let (ct, body) = multipart_body(&load_fixture("article_no_references.docx"));

    let response = server.post("/convert").content_type(&ct).bytes(body.into()).await;
    assert_eq!(response.status_code(), StatusCode::OK);

    let json: serde_json::Value = response.json();
    assert_eq!(json["success"], true, "missing refs must not crash the converter");

    let meta = &json["metadata"];
    assert_eq!(meta["reference_count"], 0);
    assert_eq!(meta["has_abstract"], true);
    assert!(meta["section_count"].as_u64().unwrap_or(0) >= 2);

    let xml = json["xml"].as_str().unwrap();
    assert!(!xml.contains("<back>"), "<back> must be absent when there are no references");
    assert!(!xml.contains("<ref-list>"));

    assert!(
        has_warning(&json["warnings"], "No references section found"),
        "extractor must warn about missing references section"
    );
    assert!(
        !has_warning(&json["warnings"], "Could not determine document title"),
        "title extraction must still succeed"
    );
    assert!(
        !has_warning(&json["warnings"], "No abstract found"),
        "abstract extraction must still succeed"
    );
}
